VER=1.2.3
URLBASE=http://chujstym

include ../../rules.mk

define fetch
	@echo muj fetch
endef

define extract
	@echo muj extract
endef

define patch
	@echo muj patch
endef

define config
	@echo muj config
endef

define build
	@echo muj build
endef

define dest
	mkdir -p dest
	@echo muj dest
endef
