VER=3.1.1
URLBASE=http://www.mpfr.org
USRSUBDIR=mpfr-current
CFGVARS=LDFLAGS="-Wl,-rpath,${FIXME}tools/lib"
CFGFLAGS=--prefix=${FIXME}/tools --enable-shared --with-gmp=${FIXME}/tools

include ../config.mk

