NAME=mpfr
VER=3.1.1
URLBASE=http://www.mpfr.org/mpfr-current
CFG_VARS=LDFLAGS="-Wl,-rpath,$(FIXME)tools/lib"
CFG_FLAGS=--prefix=$(FIXME)/tools --enable-shared --with-gmp=$(FIXME)/tools

include ../toolchain.mk
include ../../rules.mk
