VER=1.0.1
URLBASE=http://www.multiprecision.org/mpc
URLSUBDIR=download
SRCEXT=tar.gz

CFGVARS=LDFLAGS="-Wl,-rpath,${FIXME}/tools/lib"
CFGFLAGS=--prefix=${FIXME}/tools --with-gmp=${FIXME}/tools --with-mpfr=${FIXME}/tools

include ../config.mk

