VER=1.0.1
URLBASE=http://www.multiprecision.org/mpc/download
SRCEXT=tar.gz

CFG_VARS=LDFLAGS="-Wl,-rpath,${FIXME}/tools/lib"
CFG_FLAGS=--prefix=${FIXME}/tools --with-gmp=${FIXME}/tools --with-mpfr=${FIXME}/tools

include ../toolchain.mk
include ../../rules.mk
